# Generated by Django 4.1.1 on 2022-09-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_alter_weathertype_hightest_temp_and_more'),
        ('product_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weather_api.weathertype'),
        ),
    ]
