# Generated by Django 4.1.1 on 2022-09-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathertype',
            name='hightest_temp',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='weathertype',
            name='lowest_temp',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
